version: '3'

services:
  database:
    image: mongo
    container_name: database
    restart: always
    ports:
      - '27017:27017'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    
    ports:
      - '3000:3000'